/* ============================================================
   DONNEES DU JEU : questions, drapeaux, tirage des manches
   ============================================================ */
/* ============================================================
   BANQUE DE QUESTIONS
   flag : vert | rouge | bleu | jaune | blanc
   ref  : (optionnel) reference regle, affichee si presente
   ============================================================ */
var BANK = [

  /* =======================  DRAPEAU VERT  ======================= */
  {flag:"vert",theme:"Securite",scene:sceneSafety(),
   q:"Un joueur est encore devant toi, pres du green. Peux-tu taper ta balle ?",
   choices:["Oui, je vise a cote","Non, j'attends qu'il soit parti et loin","Oui si je crie avant","Oui, il n'a qu'a faire attention"],
   correct:1,hint:"La securite passe toujours avant le jeu.",
   explain:"On ne joue jamais quand quelqu'un peut etre atteint par la balle. Tu attends que la personne devant soit partie et bien a l'ecart."},
  {flag:"vert",theme:"Securite",scene:null,
   q:"Avant de faire ton swing, que verifies-tu autour de toi ?",
   choices:["Que personne n'est trop pres, devant ou derriere","Que le drapeau est bien droit","Rien, je tape","La couleur du ciel"],
   correct:0,hint:"Un club et une balle, ca peut faire mal.",
   explain:"Avant chaque coup, tu regardes que personne n'est assez pres pour etre touche par ton club (en arriere) ou par ta balle (devant)."},
  {flag:"vert",theme:"Comportement",scene:null,
   q:"Un joueur a cote de toi s'apprete a taper sa balle. Que fais-tu ?",
   choices:["Je lui parle pour l'encourager","Je bouge devant lui","Je reste silencieux et immobile","Je tape en meme temps"],
   correct:2,hint:"Au golf, on laisse le calme a celui qui joue.",
   explain:"Quand quelqu'un joue, on reste silencieux et immobile, un peu en retrait. Le bruit ou le mouvement peuvent le gener."},
  {flag:"vert",theme:"Green & pitch",scene:scenePitch(210,150,true),
   q:"Comment appelle-t-on la petite marque que la balle laisse en tombant sur le green ?",
   choices:["Un divot","Un pitch","Un bunker","Un birdie"],
   correct:1,hint:"C'est un mot court, tres utilise sur le green.",
   explain:"La marque laissee par la balle sur le green s'appelle un pitch. On apprend tres tot a le reparer pour garder un beau green."},
  {flag:"vert",theme:"Materiel",scene:sceneTool(),
   q:"Cet objet a deux dents (une fourchette). A quoi sert-il ?",
   choices:["A planter la balle","A reparer les pitchs sur le green","A ratisser le bunker","A porter le sac"],
   correct:1,hint:"On s'en sert sur le green, la ou tombe la balle.",
   explain:"C'est un releve-pitch. Il sert a reparer la marque de balle (le pitch) sur le green. On doit toujours en avoir un dans la poche. C'est le geste prefere du coach Tiger : releve ton pitch... et parfois celui des autres !"},
  {flag:"vert",theme:"Materiel",scene:sceneTee(200,115),
   q:"Pour surelever la balle au depart, on la pose sur un petit objet. C'est...",
   choices:["Un tee","Un marqueur","Un pitch","Un club"],
   correct:0,hint:"Petit piquet en bois ou plastique planté dans le sol.",
   explain:"On pose la balle sur un tee au depart. On prefere les tees en bois, et on ne les laisse pas trainer par terre apres."},
  {flag:"vert",theme:"But du jeu",scene:sceneGreen(180,150),
   q:"Au golf, quel est le but du jeu ?",
   choices:["Taper le plus fort possible","Mettre la balle dans le trou en le moins de coups possible","Aller le plus vite","Faire le plus de bruit"],
   correct:1,hint:"On compte les coups, et le moins gagne.",
   explain:"Le but est de mettre la balle dans le trou en jouant le moins de coups possible. Le drapeau montre ou se trouve le trou."},
  {flag:"vert",theme:"Comportement",scene:null,
   q:"Ton copain reussit un tres joli coup. Que fais-tu ?",
   choices:["Je fais semblant de rien","Je le felicite","Je dis que j'aurais fait mieux","Je crie tres fort"],
   correct:1,hint:"Le golf, c'est aussi apprecier le jeu des autres.",
   explain:"On felicite ses partenaires pour leurs bons coups. C'est la courtoisie du golf, et ca rend la partie plus agreable."},
  {flag:"vert",theme:"Comportement",scene:null,
   q:"Tu rates ton coup et tu es enerve. Que ne dois-tu JAMAIS faire ?",
   choices:["Respirer un bon coup","Jeter ou lancer ton club","Recommencer plus doucement","Demander un conseil au pro"],
   correct:1,hint:"Un club lance peut blesser quelqu'un.",
   explain:"On ne jette jamais son club, meme enerve : c'est dangereux et ce n'est pas respectueux. On respire et on repart calmement."},
  {flag:"vert",theme:"Etiquette",scene:null,
   q:"A la fin de la partie, que fais-tu avec tes partenaires ?",
   choices:["Je pars sans rien dire","Je les remercie (et je leur serre la main)","Je range vite mon sac","Je recompte tout"],
   correct:1,hint:"C'est une belle tradition au golf.",
   explain:"A la fin, on remercie ses partenaires et on se serre la main. C'est la politesse de fin de partie au golf."},
  {flag:"vert",theme:"Materiel",scene:sceneMarker(true),
   q:"Qu'est-ce qu'il faut toujours avoir dans sa poche pour le green ?",
   choices:["Un tee et une balle","Un releve-pitch et un marqueur","Des lunettes","Un telephone"],
   correct:1,hint:"Un pour reparer, un pour marquer la balle.",
   explain:"Sur le green, il faut un releve-pitch (pour reparer les pitchs) et un marqueur (pour marquer la place de sa balle). Toujours en poche !"},
  {flag:"vert",theme:"Green & pitch",scene:sceneGreen(180,150),
   q:"Sur le green, quel comportement abime le gazon ?",
   choices:["Marcher doucement","Trainer les pieds ou courir","Regarder ou est le trou","Poser sa balle"],
   correct:1,hint:"Le green est fragile, comme un joli tapis.",
   explain:"On marche doucement sur le green, sans trainer les pieds ni courir : le gazon du green est tres fragile et met du temps a se reparer."},
  {flag:"vert",theme:"Securite",scene:null,
   q:"Au practice, comment tape-t-on les balles en securite ?",
   choices:["Chacun a son poste, tous dans le meme sens","Chacun comme il veut","En se croisant","En marchant devant les autres"],
   correct:0,hint:"Tout le monde vise du meme cote.",
   explain:"Au practice, chacun reste a son poste et tape dans le meme sens. On ne va jamais devant les autres pendant qu'ils frappent."},
  {flag:"vert",theme:"Etiquette",scene:sceneGreen(200,138),
   q:"Le drapeau planté dans le trou sert a quoi ?",
   choices:["A decorer","A montrer ou est le trou, meme de loin","A tenir la balle","A mesurer le vent"],
   correct:1,hint:"On le voit de loin sur le parcours.",
   explain:"Le drapeau (ou 'flag') montre l'emplacement du trou, meme quand on est loin sur le trou. On le remet toujours en place a la fin."},
  {flag:"vert",theme:"Comportement",scene:null,
   q:"Un adulte te dit d'attendre avant de jouer. Que fais-tu ?",
   choices:["Je tape quand meme, je suis pret","J'attends, la securite d'abord","Je discute","Je change de trou"],
   correct:1,hint:"L'adulte voit peut-etre un danger que tu ne vois pas.",
   explain:"Si un adulte te demande d'attendre, tu attends : il voit peut-etre un joueur ou un danger. La securite passe avant l'envie de jouer."},

  /* =======================  DRAPEAU ROUGE  ======================= */
  {flag:"rouge",theme:"Green & pitch",scene:sceneMarker(true),
   q:"Ta balle est sur le green et tu veux la ramasser. Que fais-tu d'abord ?",
   choices:["Je la prends directement","Je pose un marqueur juste derriere, puis je la releve","Je la pousse du pied","Je la lance"],
   correct:1,hint:"Il faut pouvoir la remettre exactement au meme endroit.",
   explain:"Avant de relever ta balle sur le green, tu poses un marqueur juste derriere. Comme ca tu la reposes ensuite exactement a sa place."},
  {flag:"rouge",theme:"Green & pitch",scene:scenePitch(215,150),
   q:"Tu vois un pitch (marque de balle) sur le green. Que fais-tu ?",
   choices:["Rien, ce n'est pas le mien","Je le repare avec mon releve-pitch","Je marche dessus","J'appelle le pro"],
   correct:1,hint:"On repare son pitch... et souvent aussi celui des autres.",
   explain:"Un bon golfeur repare son pitch (et volontiers ceux des autres). Un pitch non repare laisse une marque qui abime le green longtemps."},
  {flag:"rouge",theme:"Green & pitch",scene:scenePitch(215,150),
   q:"Comment repare-t-on bien un pitch ?",
   choices:["On souleve la terre vers le haut","On pousse les bords vers le centre, puis on tapote","On tape avec le club","On verse de l'eau"],
   correct:1,hint:"On rapproche l'herbe vers le milieu, on ne souleve pas.",
   explain:"On plante le releve-pitch sur les bords et on pousse doucement l'herbe vers le centre du pitch, puis on tapote avec le putter. On ne souleve pas la terre (ca coupe les racines)."},
  {flag:"rouge",theme:"Regle de jeu",scene:sceneOrder(),
   q:"Sur le green, deux balles. Qui joue en premier ?",
   choices:["La balle A (la plus proche du trou)","La balle B (la plus loin du trou)","Celui qui est arrive le premier","Peu importe"],
   correct:1,hint:"Au golf, c'est le plus eloigne du trou qui joue.",
   explain:"Normalement, la balle la plus eloignee du trou joue en premier. Ici c'est la balle B. (Mais si tu es pret et que ca ne gene personne, on peut aussi jouer plus vite.)"},
  {flag:"rouge",theme:"Etiquette",scene:sceneGreen(200,138),
   q:"Tout le monde a fini le trou. Que fait-on du drapeau ?",
   choices:["On le laisse par terre","On le remet bien droit dans le trou","On l'emmene","On le pose sur le green"],
   correct:1,hint:"Le joueur suivant doit le retrouver en place.",
   explain:"Quand le trou est fini, on remet le drapeau bien droit dans le trou, pour les joueurs qui arrivent apres. On ne le pose pas sur le green."},
  {flag:"rouge",theme:"Securite",scene:sceneSafety(),
   q:"Tu veux chipper vers le green, mais des joueurs y sont encore. Tu...",
   choices:["Je tape vite avant eux","J'attends qu'ils s'eloignent","Je crie et je tape","Je vise a cote"],
   correct:1,hint:"Jamais taper vers des gens.",
   explain:"On ne joue jamais vers des personnes. Tu attends qu'elles aient quitte le green et soient a l'abri avant de chipper."},
  {flag:"rouge",theme:"Etiquette",scene:sceneGreen(180,150),
   q:"Quel endroit est interdit pour poser ton sac ?",
   choices:["A cote du green","Sur le green","Pres du trou suivant","Sur le chemin"],
   correct:1,hint:"Le green est fragile et le sac est lourd.",
   explain:"On ne pose jamais son sac (ni son chariot) sur le green : c'est lourd et ca abime le gazon. On le laisse au bord, du cote du trou suivant."},
  {flag:"rouge",theme:"Etiquette",scene:sceneRake(),
   q:"Tu viens de jouer un coup dans le bunker (le sable). Avant de partir, tu...",
   choices:["Je laisse comme ca","Je ratisse le sable avec le rateau","Je saute dedans","Je remets du sable"],
   correct:1,hint:"Le joueur suivant doit trouver un sable bien lisse.",
   explain:"Apres avoir joue dans le bunker, on le ratisse pour effacer ses traces. Ainsi le prochain joueur trouve un sable lisse."},
  {flag:"rouge",theme:"Etiquette",scene:sceneOrder(),
   q:"Sur le green, quel endroit est interdit pour marcher ?",
   choices:["Au bord du green","Sur la ligne entre la balle des autres et le trou","Derriere sa propre balle","Vers le drapeau"],
   correct:1,hint:"C'est le chemin que va suivre la balle des autres.",
   explain:"On evite de marcher sur la 'ligne de putt' des autres (entre leur balle et le trou) : nos pas y laissent des marques qui devient leur balle."},
  {flag:"rouge",theme:"Green & pitch",scene:sceneMarker(true),
   q:"Le marqueur, qu'est-ce que c'est ?",
   choices:["Un stylo","Un petit jeton pour marquer la place de la balle sur le green","Un club special","Un tee en metal"],
   correct:1,hint:"Souvent une petite piece ou un jeton plat.",
   explain:"Le marqueur est un petit jeton (ou une piece) qu'on pose derriere la balle sur le green pour marquer sa place avant de la relever."},
  {flag:"rouge",theme:"Green & pitch",scene:sceneMarker(),
   q:"Tu as marque et releve ta balle. Ou la reposes-tu ?",
   choices:["N'importe ou sur le green","Juste devant le marqueur, a sa place exacte","Plus pres du trou","Dans le trou"],
   correct:1,hint:"Le marqueur montre l'endroit exact.",
   explain:"Tu reposes la balle juste devant le marqueur, exactement a l'endroit ou elle etait, puis tu enleves le marqueur avant de jouer."},
  {flag:"rouge",theme:"Comportement",scene:null,
   q:"Ta balle rate le trou de tout pres. Comment reagis-tu ?",
   choices:["Je tape le sol de colere","Je reste calme et je continue","Je crie","J'abandonne le trou"],
   correct:1,hint:"Le golf demande de rester calme, meme quand c'est rageant.",
   explain:"On reste calme, meme apres un coup rate de peu. Se mettre en colere n'aide pas a mieux jouer et gene les autres."},
  {flag:"rouge",theme:"Rapidite",scene:null,
   q:"Pendant que les autres jouent, comment gagner du temps ?",
   choices:["Je regarde mon telephone","Je me prepare pour etre pret quand c'est mon tour","Je m'assois loin","Je range mon sac"],
   correct:1,hint:"Etre pret a l'avance fait avancer la partie.",
   explain:"On profite du temps ou les autres jouent pour reflechir a son coup et se preparer. Comme ca, quand c'est ton tour, tu es deja pret : la partie avance."},
  {flag:"rouge",theme:"Etiquette",scene:sceneBag(),
   q:"Tu arrives a pied au green. Ou poses-tu ton sac (A, B ou C) ?",
   choices:["A : sur le green","B : du cote du trou suivant","C : la ou tu es arrive","N'importe ou"],
   correct:1,hint:"On veut repartir vite... et sans abimer le green.",
   explain:"On pose son sac du cote du trou suivant (B), jamais sur le green (A). Comme ca, une fois le trou fini, on repart tout de suite sans revenir en arriere."},
  {flag:"rouge",theme:"Materiel",scene:sceneTool(),
   q:"Rappel : cet objet a deux dents, c'est le releve-pitch. Quand l'utilises-tu ?",
   choices:["Dans le bunker","Sur le green, pour reparer les pitchs","Au depart","Jamais"],
   correct:1,hint:"Sur le green, la ou la balle laisse des marques.",
   explain:"Le releve-pitch s'utilise sur le green pour reparer les marques de balle (les pitchs). Un bon reflexe a chaque passage sur un green."},

  /* =======================  DRAPEAU BLEU  ======================= */
  {flag:"bleu",theme:"Regle de jeu",scene:sceneTee(200,120),
   q:"Au depart, ou as-tu le droit de poser ta balle ?",
   choices:["Devant les marques","Entre les deux marques (jamais devant)","A cote des marques","Ou tu veux sur le trou"],
   correct:1,hint:"Jamais devant les plots de depart.",
   explain:"On joue depuis l'espace entre les deux marques de depart, jamais devant. C'est l'aire de depart."},
  {flag:"bleu",theme:"Regle de jeu",scene:sceneTee(200,138),
   q:"Peux-tu reculer un peu derriere les marques pour jouer ?",
   choices:["Non, il faut etre juste sur la ligne","Oui, jusqu'a 2 longueurs de club derriere","Oui, autant que je veux","Non, jamais"],
   correct:1,hint:"Un petit rectangle, pas seulement une ligne.",
   explain:"L'aire de depart est un rectangle : entre les marques, et jusqu'a 2 longueurs de club vers l'arriere. Tu peux reculer un peu, mais pas avancer devant."},
  {flag:"bleu",theme:"Rapidite",scene:sceneOrder(),
   q:"En jeu, qui joue normalement en premier ?",
   choices:["Le plus jeune","Le plus loin du trou (mais tu peux jouer si tu es pret et que ca ne gene personne)","Le plus proche du trou","Toujours le meme"],
   correct:1,hint:"Le plus loin d'abord... mais on peut aller plus vite si c'est sur.",
   explain:"Normalement, la balle la plus eloignee du trou joue en premier. Mais pour ne pas perdre de temps, tu peux jouer des que tu es pret, si c'est sans danger : c'est le 'jeu rapide'."},
  {flag:"bleu",theme:"Rapidite",scene:sceneBag(),
   q:"En arrivant au green, ou poses-tu ton sac pour repartir vite ?",
   choices:["A : sur le green","B : du cote du trou suivant","C : loin derriere","Sur le drapeau"],
   correct:1,hint:"Du cote de la sortie, pour ne pas revenir sur ses pas.",
   explain:"On pose le sac du cote du trou suivant (B). Jamais sur le green. Ainsi, le trou fini, on part directement : c'est bon pour le rythme de jeu."},
  {flag:"bleu",theme:"Score",scene:null,
   q:"Tu as deja joue 8 coups sur le meme trou et la balle n'est pas rentree. Que fais-tu ?",
   choices:["Je continue jusqu'a la rentrer","Je releve la balle, je note le score maximum et je passe au trou suivant","J'abandonne la partie","Je recommence le trou"],
   correct:1,hint:"Il existe un 'score maximum' pour ne pas se decourager.",
   explain:"Avec le 'score maximum', au bout de 8 coups tu releves ta balle, tu notes le score prevu et tu passes au trou suivant. Ca evite de se decourager et ca fait avancer la partie."},
  {flag:"bleu",theme:"Score",scene:null,
   q:"Qui compte tes coups pendant la partie ?",
   choices:["Personne","Je compte tous mes coups moi-meme, honnetement","Seulement l'adulte","On ne compte pas"],
   correct:1,hint:"Le golf est un sport d'honnetete.",
   explain:"Chaque joueur compte tous ses coups, honnetement, y compris les coups rates. L'honnetete est une valeur importante au golf."},
  {flag:"bleu",theme:"Regle de jeu",scene:sceneTee(200,120),
   q:"Apres le 1er trou, qui a 'l'honneur' (joue en premier) au depart suivant ?",
   choices:["Le plus grand","Celui qui a fait le meilleur score au trou d'avant","Le plus jeune","Celui qui veut"],
   correct:1,hint:"Le meilleur du trou precedent est recompense.",
   explain:"Celui qui a fait le meilleur score au trou precedent a 'l'honneur' : il joue en premier au depart du trou suivant."},
  {flag:"bleu",theme:"Regle de jeu",scene:sceneWaterRed(268,150),
   q:"Ta balle tombe dans l'eau, entre des piquets rouges ou jaunes. Est-elle perdue pour toujours ?",
   choices:["Oui, tant pis","Non : je peux repartir en ajoutant 1 coup de penalite","Non, je vais la chercher dans l'eau","Oui, je passe au trou suivant"],
   correct:1,hint:"L'eau, c'est une 'zone a penalite', pas la fin.",
   explain:"Une balle dans l'eau (zone a penalite, piquets rouges ou jaunes) n'est pas perdue pour de bon : tu peux repartir en ajoutant 1 coup de penalite."},
  {flag:"bleu",theme:"Regle de jeu",scene:sceneTrees(150,140),
   q:"Tu ne retrouves pas ta balle dans les arbres. Combien de temps peux-tu chercher ?",
   choices:["1 minute","3 minutes","10 minutes","Le temps que tu veux"],
   correct:1,hint:"C'est assez court, il faut chercher vite.",
   explain:"Tu as 3 minutes pour chercher ta balle. Passe ce temps, elle est perdue et tu rejoues d'ou tu venais avec 1 coup de penalite."},
  {flag:"bleu",theme:"Etiquette",scene:sceneDivot(),
   q:"En tapant, tu as arrache une motte de gazon (un divot) sur le fairway. Que fais-tu ?",
   choices:["Je la laisse","Je la remets dans le trou et j'appuie dessus","Je la jette au loin","Je la mets dans ma poche"],
   correct:1,hint:"On repare le gazon qu'on abime.",
   explain:"On ramasse la motte (le divot) et on la remet dans son trou en appuyant dessus, pour que le gazon repousse. C'est prendre soin du parcours."},
  {flag:"bleu",theme:"Rapidite",scene:null,
   q:"Le groupe derriere vous joue plus vite et vous attend souvent. Que faites-vous ?",
   choices:["On joue encore plus lentement","On les laisse passer devant","On accelere en courant","On ne fait rien"],
   correct:1,hint:"Politesse et rythme : on ne bloque pas les plus rapides.",
   explain:"Si le groupe derriere est plus rapide et vous attend, la politesse est de le laisser passer. On l'invite a jouer devant a un moment sur."},
  {flag:"bleu",theme:"Comportement",scene:null,
   q:"Un joueur d'un autre trou, a cote, s'apprete a jouer. Tu...",
   choices:["Je continue a parler fort","J'attends et je reste silencieux","Je passe devant lui","Je tape pour le presser"],
   correct:1,hint:"Le calme vaut aussi entre trous voisins.",
   explain:"Meme si ce n'est pas ton groupe, tu attends et tu restes silencieux pendant qu'un joueur proche s'apprete a jouer. C'est le respect au golf."},
  {flag:"bleu",theme:"Materiel",scene:null,
   q:"Combien de clubs peut-on avoir au maximum dans son sac ?",
   choices:["10","14","18","Autant qu'on veut"],
   correct:1,hint:"Un chiffre pair, connu des joueurs.",
   explain:"Maximum 14 clubs dans le sac. On peut en avoir moins, ce n'est pas grave, surtout quand on debute."},
  {flag:"bleu",theme:"Materiel",scene:null,
   q:"Combien de balles au minimum dois-tu avoir sur toi avant de partir jouer ?",
   choices:["Aucune, il y en a sur le parcours","Au moins 2","Exactement 1","Au moins 10"],
   correct:1,hint:"Pense au cas ou tu dois jouer une balle 'provisoire'.",
   explain:"On garde toujours au moins 2 balles sur soi. Comme ca, si on doit rejouer ou jouer une balle provisoire (balle peut-etre perdue ou hors limites), on en a toujours une prete."},
  {flag:"bleu",theme:"Securite",scene:null,
   q:"Avant de taper ton coup de depart, tu verifies surtout que...",
   choices:["Le trou est loin","Personne n'est devant ni trop pres","La balle est propre","Le vent est bon"],
   correct:1,hint:"La securite avant tout.",
   explain:"Avant chaque depart, tu regardes que le groupe devant est bien parti et hors de portee, et que personne n'est trop pres de toi."},
  {flag:"bleu",theme:"Etiquette",scene:sceneRake(),
   q:"Tu sors du bunker apres ton coup. Que fais-tu du sable ?",
   choices:["Rien","Je ratisse pour effacer mes traces","Je le tasse avec le pied","Je le mouille"],
   correct:1,hint:"Sable lisse pour le joueur suivant.",
   explain:"On ratisse le bunker apres son passage, puis on repose le rateau la ou le club l'a indique (souvent a l'exterieur, pres du bord)."},

  /* =======================  DRAPEAU JAUNE  ======================= */
  {flag:"jaune",theme:"Regle de jeu",ref:"Regle 18",scene:sceneOB(240,150),
   q:"Les piquets BLANCS sur un parcours marquent quoi ?",
   choices:["De l'eau","La limite du terrain (hors limites)","Un terrain en reparation","Le chemin"],
   correct:1,hint:"Blanc = la frontiere du terrain.",
   explain:"Les piquets ou lignes blanches marquent le hors limites. Si ta balle est entierement au-dela, elle est hors limites : tu rejoues d'ou tu venais avec 1 coup de penalite."},
  {flag:"jaune",theme:"Regle de jeu",ref:"Regle 17",scene:sceneWaterYellow(200,165),
   q:"Ta balle est dans une zone a penalite (piquets rouges ou jaunes). Que peux-tu faire ?",
   choices:["Rien, elle est perdue","Te degager en ajoutant 1 coup de penalite","La jouer sans penalite obligatoirement","Recommencer le trou"],
   correct:1,hint:"On peut toujours repartir pour 1 coup.",
   explain:"Dans une zone a penalite, tu peux te degager pour 1 coup de penalite (ou parfois jouer la balle telle quelle si tu peux). Les piquets rouges ou jaunes montrent cette zone."},
  {flag:"jaune",theme:"Regle de jeu",ref:"Regle 17",scene:sceneWaterRed(215,175,'<path d="M235 100 Q260 150 218 172" fill="none" stroke="#fff" stroke-width="2" stroke-dasharray="4 4"/>'),
   q:"Ta balle rentre dans l'eau puis RESSORT et s'arrete sur l'herbe. Que se passe-t-il ?",
   choices:["1 coup de penalite","Je la joue normalement, sans penalite","Je dois la remettre dans l'eau","Elle est perdue"],
   correct:1,hint:"Ce qui compte, c'est ou elle s'arrete.",
   explain:"Une balle n'est dans l'eau que si elle s'y arrete. Si elle ressort et repose sur l'herbe, tu la joues normalement, sans penalite."},
  {flag:"jaune",theme:"Regle de jeu",ref:"Regle 12",scene:sceneBunker(180,155),
   q:"Ta balle est dans le bunker. Qu'est-ce qui est interdit avant de jouer ?",
   choices:["Enlever une feuille","Toucher le sable pour le tester","Regarder la balle","Poser son sac dehors"],
   correct:1,hint:"On ne 'teste' jamais le sable.",
   explain:"Dans le bunker, tu ne dois pas tester le sable ni le toucher juste derriere ta balle avant de jouer. Sinon, penalite. (Enlever une feuille est permis.) Et souviens-toi : pour Tiger, le bunker est le coup le plus facile du golf !"},
  {flag:"jaune",theme:"Etiquette",scene:sceneRake(),
   q:"Apres ton coup dans le bunker, quel est le bon reflexe ?",
   choices:["Partir vite","Ratisser le sable derriere soi","Sauter dehors","Laisser le rateau dans le trou"],
   correct:1,hint:"On laisse le bunker propre.",
   explain:"On ratisse le bunker apres son passage pour effacer les traces, puis on repose le rateau proprement au bord. Le joueur suivant retrouve un sable lisse."},
  {flag:"jaune",theme:"Regle de jeu",ref:"Regle 9",scene:sceneFairway(180,150),
   q:"Sur le fairway, un coup de vent fait rouler ta balle un peu plus loin. Que fais-tu ?",
   choices:["Je la remets a sa place","Je la joue d'ou elle est maintenant, sans penalite","Je compte 1 coup","Je la remets sur un tee"],
   correct:1,hint:"Le vent, ce n'est pas toi.",
   explain:"Quand le vent deplace ta balle (hors green), tu la joues de son nouvel endroit, sans penalite. Tu n'y es pour rien."},
  {flag:"jaune",theme:"Regle de jeu",ref:"Regle 15",scene:sceneFairway(200,150,'<path d="M180 138 q6 -6 12 0" stroke="#6d5a2a" stroke-width="2" fill="none"/><circle cx="216" cy="142" r="3" fill="#7a6a3a"/>'),
   q:"Une feuille et un petit caillou sont juste a cote de ta balle. Peux-tu les enlever ?",
   choices:["Non, jamais","Oui, mais attention a ne pas faire bouger la balle","Seulement sur le green","Oui, sans aucun risque"],
   correct:1,hint:"On peut les enlever, mais la balle ne doit pas bouger.",
   explain:"Tu peux enlever les detritus (feuilles, brindilles, cailloux) partout. Mais si la balle bouge a cause de ca (hors green), c'est 1 coup de penalite et tu la remets."},
  {flag:"jaune",theme:"Regle de jeu",ref:"Regle 18",scene:sceneTrees(150,140),
   q:"Ta balle est vraiment perdue apres 3 minutes de recherche. Que fais-tu ?",
   choices:["Je continue de chercher","Je rejoue d'ou j'avais joue, avec 1 coup de penalite","Je pose une balle sur place","Je passe au trou suivant"],
   correct:1,hint:"On repart du point du coup precedent.",
   explain:"Balle perdue = tu retournes rejouer du point du coup precedent, avec 1 coup de penalite (c'est la regle 'distance et coup')."},
  {flag:"jaune",theme:"Securite",scene:sceneFairway(180,150),
   q:"Ta balle part tout droit vers d'autres joueurs. Que cries-tu pour les prevenir ?",
   choices:["Attention","Balle ! (ou 'Fore !')","Pardon","Rien"],
   correct:1,hint:"C'est le cri d'alerte connu de tous les golfeurs.",
   explain:"Si ta balle part vers des personnes, tu cries fort 'Balle !' (ou 'Fore !'). C'est le signal d'alerte pour qu'elles se protegent la tete."},
  {flag:"jaune",theme:"Regle de jeu",ref:"Regle 16",scene:sceneCartPath(78,150),
   q:"Ta balle repose SUR le chemin en dur (des voiturettes). Que peux-tu faire ?",
   choices:["Jouer depuis le chemin","Te degager gratuitement juste a cote","Te degager avec 1 penalite","Reculer au depart"],
   correct:1,hint:"Un chemin en dur n'est pas fait pour jouer dessus.",
   explain:"Le chemin en dur donne droit a un degagement GRATUIT (sans penalite) : tu te degages a l'endroit le plus proche a cote, pas plus pres du trou."},
  {flag:"jaune",theme:"Green & pitch",ref:"Regle 13",scene:sceneGreen(200,138),
   q:"Tu puttes en laissant le drapeau dans le trou, et ta balle le tape. Penalite ?",
   choices:["Oui, 2 coups","Oui, 1 coup","Non, aucune penalite","Il faut rejouer"],
   correct:2,hint:"On a le droit de garder le drapeau pour putter.",
   explain:"Tu peux putter avec le drapeau reste dans le trou. Si ta balle le touche, aucune penalite : elle est jouee comme elle repose."},
  {flag:"jaune",theme:"Score",scene:null,
   q:"Tu as pris 1 coup de penalite dans l'eau. Que fais-tu de ce coup ?",
   choices:["Je l'oublie","Je l'ajoute a mon score du trou","Je l'enleve","Je le donne a un autre"],
   correct:1,hint:"Les penalites comptent dans le score.",
   explain:"Un coup de penalite s'ajoute a ton score du trou, comme un coup joue. Compter juste, penalites comprises, fait partie du jeu."},
  {flag:"jaune",theme:"Etiquette",scene:sceneGreen(180,150),
   q:"Prendre soin du parcours, c'est faire quoi ?",
   choices:["Rien de special","Remettre les divots, ratisser les bunkers, reparer les pitchs","Courir sur le green","Laisser ses tees partout"],
   correct:1,hint:"On laisse le parcours aussi beau qu'on l'a trouve.",
   explain:"Prendre soin du parcours, c'est remettre les mottes (divots), ratisser les bunkers et reparer les pitchs. On laisse le terrain propre pour les suivants."},
  {flag:"jaune",theme:"Securite",scene:sceneFairway(180,160),
   q:"Des joueurs devant vont taper leur coup. Peux-tu traverser le fairway devant eux ?",
   choices:["Oui, vite fait","Non, j'attends qu'ils aient joue et soient loin","Oui si je cours","Oui en faisant signe"],
   correct:1,hint:"On ne passe jamais devant des joueurs qui vont frapper.",
   explain:"On ne traverse jamais devant des joueurs qui s'appretent a taper. Tu attends qu'ils aient joue et que ce soit sans danger."},

  /* =======================  DRAPEAU BLANC  ======================= */
  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 19",scene:sceneTrees(200,150),
   q:"Ta balle est coincee sous un arbre, injouable. Combien d'options as-tu (1 coup chacune) ?",
   choices:["Une seule","Trois : rejouer d'ou tu venais, dropper en arriere, ou dropper a cote (2 longueurs)","Deux","Aucune"],
   correct:1,hint:"Trois options, comme pour une zone rouge.",
   explain:"Balle injouable = 3 options a 1 coup chacune : rejouer du point precedent, dropper en arriere sur la ligne, ou dropper sur le cote dans 2 longueurs de club (pas plus pres du trou). C'est toi qui decides."},
  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 14",scene:sceneFairway(200,150,'<line x1="200" y1="118" x2="200" y2="146" stroke="#fff" stroke-width="2" stroke-dasharray="3 4"/><text x="238" y="132" font-family="Helvetica" font-size="11" fill="#20301f">genou</text>'),
   q:"Quand tu dois 'dropper' ta balle, de quelle hauteur la laisses-tu tomber ?",
   choices:["De l'epaule","De la hauteur du genou","Contre le sol","Peu importe"],
   correct:1,hint:"Ni tout en haut, ni tout en bas.",
   explain:"On drope de la hauteur du genou, debout. Un drop de l'epaule ou trop bas doit etre recommence."},
  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 18.3",scene:sceneOB(160,150),
   q:"Tu crains que ta balle soit perdue ou hors limites. Que fais-tu avant d'aller chercher ?",
   choices:["Je joue une balle en cachette","J'annonce 'balle provisoire' et j'en joue une","Je pars chercher direct","Je demande a l'arbitre"],
   correct:1,hint:"Le mot 'provisoire' doit etre dit avant.",
   explain:"Tu annonces clairement 'balle provisoire' AVANT d'aller chercher. Si l'originale est perdue ou hors limites, la provisoire devient ta balle en jeu."},
  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 17",scene:sceneWaterRed(268,150),
   q:"Zone a penalite ROUGE : combien d'options de degagement (en plus de jouer la balle telle quelle) ?",
   choices:["Une","Deux","Trois","Aucune"],
   correct:2,hint:"Le rouge a une option de plus que le jaune.",
   explain:"Zone rouge (1 coup) : rejouer d'ou tu venais, dropper en arriere sur la ligne, ou dropper sur le cote (2 longueurs). Le jaune n'a pas l'option laterale."},
  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 17.1",scene:sceneWaterRed(285,140,markX(252,120)+label(252,105,"passage")),
   q:"Pour te degager d'une zone rouge, a partir de quel point mesures-tu ?",
   choices:["La ou la balle est dans l'eau","Le point ou elle a franchi le bord (la croix)","Le milieu de l'eau","Le trou"],
   correct:1,hint:"Jamais l'endroit final dans l'eau.",
   explain:"On part du point ou la balle a franchi le bord de la zone (la croix). C'est de la que tu mesures tes 2 longueurs pour le degagement lateral."},
  {flag:"blanc",theme:"Regle de jeu",ref:"Definitions",scene:sceneFairway(200,150),
   q:"Pour mesurer 'une longueur de club', quel club utilises-tu ?",
   choices:["Le putter","Un fer 7","Le club le plus long du sac (sauf le putter), souvent le driver","Un club au hasard"],
   correct:2,hint:"Le plus long pour avoir le plus de place.",
   explain:"La longueur de club se mesure avec le club le plus long du sac hors putter (le driver en general). Elle sert aux zones de 1 ou 2 longueurs."},
  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 16.3",scene:sceneEmbedded(200,150),
   q:"Ta balle est enfoncee dans son propre trou (dans la terre molle) sur le fairway. Que peux-tu faire ?",
   choices:["Rien, je joue telle quelle","Me degager gratuitement juste derriere le trou","Me degager avec 1 penalite","La deterrer a la main"],
   correct:1,hint:"Une balle enfoncee dans l'herbe tondue donne droit a de l'aide gratuite.",
   explain:"Une balle enfoncee dans sa propre marque (zone gazonnee) donne droit a un degagement GRATUIT : tu drops dans 1 longueur juste derriere l'endroit ou elle etait plantee."},
  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 6.3c",scene:sceneTrees(200,150,'<circle cx="240" cy="150" r="7" fill="#fff" stroke="#c81d25" stroke-dasharray="2 2"/>'),
   q:"Tu joues par erreur la balle d'un autre joueur. Que se passe-t-il ?",
   choices:["Rien si je n'avais pas vu","2 coups de penalite, et je dois retrouver et jouer ma vraie balle","1 coup de penalite","Je continue avec"],
   correct:1,hint:"D'ou l'interet de marquer sa balle au feutre !",
   explain:"Jouer une 'mauvaise balle' = 2 coups de penalite, et tu dois corriger en jouant ta vraie balle. Marque toujours ta balle d'un signe pour la reconnaitre."},
  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 10.2",scene:null,
   q:"Tu demandes a un adversaire quel club utiliser. Autorise ?",
   choices:["Oui, c'est normal","Non : demander ce conseil, c'est 2 coups de penalite","Oui, une seule fois","Seulement sur le green"],
   correct:1,hint:"Demander quel club a un adversaire, c'est un 'conseil'.",
   explain:"Demander (ou donner) un conseil comme le choix du club a un joueur qui n'est pas ton partenaire = 2 coups de penalite. Les infos publiques (distance, position du drapeau) restent permises."},
  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 14.3c",scene:sceneFairway(200,150),
   q:"Tu drops, mais la balle roule hors de la zone autorisee. Que fais-tu ?",
   choices:["Je la joue quand meme","Je redrops une fois ; si ca rate encore, je la POSE","Je compte 1 coup","Je recommence tout"],
   correct:1,hint:"Deux essais de drop, puis on pose.",
   explain:"Si la balle dropee sort de la zone, tu redrops une 2e fois. Si elle roule encore dehors, tu la POSES a l'endroit ou elle a touche le sol au 2e drop."},
  {flag:"blanc",theme:"Green & pitch",ref:"Regle 13.3",scene:sceneGreen(244,102),
   q:"Ta balle est en equilibre au bord du trou. Combien de temps peux-tu attendre ?",
   choices:["Le temps que je veux","Environ 10 secondes une fois arrive au trou","1 minute","3 minutes"],
   correct:1,hint:"Un petit compte a rebours.",
   explain:"Tu as le temps d'arriver au trou, puis environ 10 secondes. Apres, si elle tombe, ca compte mais avec 1 coup de penalite."},
  {flag:"blanc",theme:"Green & pitch",ref:"Regle 11",scene:sceneGreen(210,150,'<circle cx="250" cy="150" r="7" fill="#ffd54f" stroke="#c9a227"/>'),
   q:"Tu puttes et ta balle tape une autre balle posee sur le green. Que se passe-t-il ?",
   choices:["Rien","2 coups de penalite pour toi, et on remet l'autre balle","1 coup pour l'autre joueur","Je rejoue sans penalite"],
   correct:1,hint:"Deux balles sur le green + un putt = attention.",
   explain:"Si ta balle puttee depuis le green tape une autre balle qui y etait posee, c'est 2 coups de penalite pour toi ; on remet l'autre balle a sa place. C'est pour ca qu'on marque les balles sur le green."},
  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 16.1",scene:sceneGUR(200,132,'water'),
   q:"Apres la pluie, ta balle est dans une flaque d'eau sur le fairway. Est-ce une zone a penalite ?",
   choices:["Oui, 1 coup de penalite","Non : c'est de l'eau temporaire, degagement gratuit","Non, je ne peux rien faire","Oui, balle perdue"],
   correct:1,hint:"Une flaque de pluie n'est pas un obstacle d'eau.",
   explain:"Une flaque de pluie est de l'eau temporaire : degagement GRATUIT a l'endroit le plus proche au sec (pas plus pres du trou), dans 1 longueur de club."},
  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 16.1",scene:sceneGUR(200,130,'gur'),
   q:"Ta balle est dans une zone marquee 'G.U.R.' (terrain en reparation). Es-tu oblige de te degager ?",
   choices:["Oui, obligatoire","Non : le degagement gratuit est un droit, tu peux aussi jouer la balle","Oui, avec 1 coup","Non, tu dois attendre"],
   correct:1,hint:"C'est une aide offerte, pas une obligation.",
   explain:"Le degagement d'un terrain en reparation est gratuit mais facultatif : tu peux jouer la balle telle quelle si tu preferes."},
  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 16.1a",scene:sceneCartPath(120,150,'<path d="M120 150 L60 150" stroke="#c81d25" stroke-width="2" stroke-dasharray="4 4"/>'),
   q:"Le chemin en dur te gene seulement pour VOIR le drapeau (ta balle est sur l'herbe). Degagement gratuit ?",
   choices:["Oui, la gene visuelle suffit","Non : pas de degagement juste pour la ligne de vue","Oui, avec 1 coup","Seulement le week-end"],
   correct:1,hint:"Le degagement couvre la balle, les pieds, le swing... pas la vue.",
   explain:"On a droit au degagement d'une obstruction seulement si elle gene la balle, le stance (les pieds) ou le mouvement de swing. Etre gene juste pour voir le drapeau ne compte pas."},
  {flag:"blanc",theme:"Rapidite",scene:sceneOrder(),
   q:"Pour jouer vite et bien, quel est le bon reflexe ?",
   choices:["Attendre son tour sans rien preparer","Se preparer pendant que les autres jouent, et jouer des qu'on est pret en securite","Courir entre les coups","Jouer tres lentement"],
   correct:1,hint:"Prepare a l'avance, joue en securite des que possible.",
   explain:"Le 'jeu rapide' : tu prepares ton coup pendant que les autres jouent, et tu joues des que tu es pret si c'est sans danger. C'est essentiel pour ne pas ralentir la partie."},
  {flag:"blanc",theme:"Etiquette",scene:sceneRake(),
   q:"Meme en autonomie (tu joues seul), que fais-tu apres etre passe dans un bunker ?",
   choices:["Rien, je suis presse","Je ratisse et je repose le rateau proprement","Je laisse mes traces","Je remets du sable a la main"],
   correct:1,hint:"L'etiquette ne s'arrete jamais, meme quand personne ne regarde.",
   explain:"L'autonomie du drapeau blanc, c'est jouer seul en respectant TOUT : on ratisse le bunker, on repare pitchs et divots, on laisse passer les plus rapides. Le savoir-etre reste essentiel."},

  /* ---- AJOUTS : plus de variete ---- */
  {flag:"vert",theme:"Etiquette",scene:null,
   q:"Sur le parcours, comment parle-t-on ?",
   choices:["Tres fort pour s'amuser","Doucement, a voix basse","On chante","On siffle"],correct:1,
   hint:"Le calme aide tout le monde a se concentrer.",
   explain:"On parle a voix basse sur le parcours, surtout quand quelqu'un se prepare a jouer. Le golf aime le calme."},
  {flag:"vert",theme:"Securite",scene:null,
   q:"Tu portes ton club en marchant. A quoi fais-tu attention ?",
   choices:["A le faire tourner vite","A ne toucher personne autour de toi","A courir avec","A viser les copains"],correct:1,
   hint:"Un club, ca depasse et ca peut cogner.",
   explain:"On porte son club calmement, sans le faire tournoyer, pour ne blesser personne autour de soi."},
  {flag:"vert",theme:"Comportement",scene:null,
   q:"Tu perds ta balle et tu es un peu decu. Que fais-tu ?",
   choices:["Je me fache","Je reste calme et j'en prends une autre","J'arrete de jouer","Je boude"],correct:1,
   hint:"On a toujours des balles de rechange dans la poche.",
   explain:"Perdre une balle arrive a tout le monde. On reste calme et on en prend une autre : c'est pour ca qu'on en a plusieurs sur soi."},
  {flag:"vert",theme:"Green & pitch",scene:sceneGreen(180,150),
   q:"Comment s'appelle la zone d'herbe tres courte autour du trou ?",
   choices:["Le fairway","Le green","Le bunker","Le rough"],correct:1,
   hint:"C'est la qu'on fait rouler la balle vers le trou.",
   explain:"Le green est la zone d'herbe tres courte autour du trou. C'est la qu'on 'putte' pour faire rouler la balle jusqu'au trou."},
  {flag:"vert",theme:"Materiel",scene:null,
   q:"Avec quoi frappe-t-on la balle de golf ?",
   choices:["La main","Un club (un baton de golf)","Le pied","Une raquette"],correct:1,
   hint:"On en a plusieurs sortes dans le sac.",
   explain:"On frappe la balle avec un club. Il en existe plusieurs : le driver pour aller loin, les fers, le wedge, et le putter pour le green."},
  {flag:"vert",theme:"Rapidite",scene:null,
   q:"Quand c'est a toi de jouer et que tu es pret, tu...",
   choices:["Attends longtemps","Joues sans trainer (mais en securite)","Laisses ton tour","Recommences ton echauffement"],correct:1,
   hint:"On evite de faire attendre les autres.",
   explain:"Quand c'est ton tour et que tu es pret, tu joues sans trainer, apres avoir verifie que c'est sans danger. La partie est plus agreable pour tous."},

  {flag:"rouge",theme:"Comportement",scene:sceneTrees(150,150),
   q:"Un partenaire cherche sa balle perdue. Que fais-tu ?",
   choices:["Je regarde ailleurs","Je l'aide a chercher","Je pars devant","Je me moque"],correct:1,
   hint:"A plusieurs, on cherche plus vite.",
   explain:"On aide ses partenaires a chercher une balle perdue. C'est plus sympa et ca fait gagner du temps a tout le monde."},
  {flag:"rouge",theme:"Etiquette",scene:sceneGreen(210,150),
   q:"En attendant ton tour sur le green, ou te places-tu ?",
   choices:["Devant celui qui joue","Un peu en retrait, hors de sa vue et de sa ligne","Sur le trou","Sur la ligne de sa balle"],correct:1,
   hint:"On ne gene ni la vue ni la ligne des autres.",
   explain:"On se place un peu en retrait, sans se tenir dans le champ de vision du joueur ni sur la ligne de sa balle vers le trou."},
  {flag:"rouge",theme:"Green & pitch",scene:scenePitch(215,150),
   q:"Pourquoi est-ce important de reparer les pitchs ?",
   choices:["Pour decorer","Pour que le green reste lisse et que les balles roulent droit","Pour gagner des points","Ce n'est pas important"],correct:1,
   hint:"Un pitch non repare fait une bosse longtemps.",
   explain:"Un pitch non repare laisse une bosse qui abime le green et fait devier les balles. En le reparant, on garde un green lisse pour tout le monde."},
  {flag:"rouge",theme:"Etiquette",scene:sceneRake(),
   q:"Apres avoir ratisse, ou reposes-tu le rateau ?",
   choices:["Au milieu du bunker","Pres du bord, la ou il gene le moins","Dans le trou","Sur le green"],correct:1,
   hint:"Il ne doit gener ni les joueurs ni les balles.",
   explain:"On repose le rateau proprement, en general a l'exterieur ou tout au bord du bunker, la ou il gene le moins le jeu."},
  {flag:"rouge",theme:"Securite",scene:sceneSafety(),
   q:"Avant de chipper vers le green, tu verifies quoi ?",
   choices:["La couleur du drapeau","Que personne n'est sur le green ni devant","Le vent","Ta montre"],correct:1,
   hint:"On ne joue jamais vers des gens.",
   explain:"Avant de chipper, tu regardes que le green est libre et que personne n'est devant toi a portee de balle."},
  {flag:"rouge",theme:"Rapidite",scene:sceneBag(),
   q:"Tu viens de finir le trou. Quand notes-tu ton score ?",
   choices:["Sur le green, tranquillement","En marchant vers le depart suivant, pour liberer le green","Jamais","Au clubhouse seulement"],correct:1,
   hint:"On quitte vite le green pour le groupe derriere.",
   explain:"On quitte le green rapidement une fois le trou fini, et on note le score en marchant vers le trou suivant. Ca evite de bloquer les joueurs derriere."},

  {flag:"bleu",theme:"Regle de jeu",scene:sceneTrees(170,150),
   q:"Ta balle est dans l'herbe haute (le rough) mais tu peux la jouer. Que fais-tu ?",
   choices:["Je la deplace sur le fairway","Je la joue comme elle est","Je la prends a la main","Je compte 1 penalite"],correct:1,
   hint:"On joue la balle la ou elle repose.",
   explain:"Regle de base du golf : on joue la balle comme elle repose, meme dans le rough. On ne la deplace pas pour se faciliter la vie."},
  {flag:"bleu",theme:"Regle de jeu",scene:sceneTee(200,120),
   q:"Tu fais ton swing mais tu rates completement la balle (tu tapes dans le vide). Ca compte ?",
   choices:["Non, on recommence","Oui, ca compte 1 coup","Seulement la 2e fois","Non, c'est un essai"],correct:1,
   hint:"Des que tu tentes de frapper, c'est un coup.",
   explain:"Un coup ou l'on rate la balle en essayant de la frapper compte comme un coup joue. La balle, elle, reste en jeu la ou elle est."},
  {flag:"bleu",theme:"Score",scene:null,
   q:"Le 'par' d'un trou, c'est quoi ?",
   choices:["Le nombre de coups prevu pour bien jouer le trou","Le nombre de joueurs","La longueur du trou","Le numero du trou"],correct:0,
   hint:"Faire le par, c'est jouer le trou 'comme prevu'.",
   explain:"Le par est le nombre de coups prevu pour bien jouer un trou (souvent 3, 4 ou 5). Finir en dessous du par, c'est tres bien joue !"},
  {flag:"bleu",theme:"Materiel",scene:null,
   q:"Avant de partir jouer, qu'est-ce qui doit etre dans ton sac ?",
   choices:["Rien de special","Des balles, des tees, un releve-pitch, un marqueur et de l'eau","Juste un club","Un ballon"],correct:1,
   hint:"On prepare son sac comme un bon padawan.",
   explain:"Un sac bien prepare : plusieurs balles, des tees, un releve-pitch, un marqueur, de l'eau et un petit encas. Comme ca, on est pret a tout."},
  {flag:"bleu",theme:"Etiquette",scene:sceneTee(200,120),
   q:"Avec ton chariot ou ton sac, quel endroit est interdit ?",
   choices:["Sur le fairway","Sur les departs et les greens","Sur le chemin","Dans le rough"],correct:1,
   hint:"Les zones tondues tres court sont fragiles.",
   explain:"On ne fait jamais rouler son chariot sur les departs ni sur les greens : ce sont des zones fragiles. On les contourne."},
  {flag:"bleu",theme:"Securite",scene:sceneFairway(180,160),
   q:"Le groupe devant est encore a portee de ta balle. Tu joues quand ?",
   choices:["Tout de suite","Quand il est hors d'atteinte","Je crie et je joue","Jamais"],correct:1,
   hint:"On attend que ce soit vraiment sans danger.",
   explain:"On attend que le groupe devant soit hors de portee avant de jouer. Mieux vaut patienter quelques secondes que de risquer de blesser quelqu'un."},

  {flag:"jaune",theme:"Regle de jeu",ref:"Regle 8",scene:sceneOB(230,150),
   q:"Ta balle est juste contre un piquet BLANC de hors-limite. Peux-tu enlever le piquet pour jouer ?",
   choices:["Oui, comme un rateau","Non, les piquets de hors-limite ne s'enlevent pas","Oui, avec 1 penalite","Seulement le tien"],correct:1,
   hint:"Ces piquets definissent la limite du terrain.",
   explain:"Les piquets de hors-limite ne se retirent pas : ils marquent la limite du terrain. On joue avec, ou on declare la balle injouable."},
  {flag:"jaune",theme:"Regle de jeu",ref:"Regle 7.2",scene:sceneTrees(180,150),
   q:"Deux balles se ressemblent. Comment etre sur que c'est la tienne ?",
   choices:["Je devine","Je l'ai marquee d'un signe avant de partir","Je prends la plus proche","Je demande a un copain"],correct:1,
   hint:"Un bon reflexe : marquer sa balle au feutre.",
   explain:"On marque sa balle d'un signe distinctif (un point, une initiale) avant de jouer. Comme ca, on la reconnait a coup sur et on evite les mauvaises balles."},
  {flag:"jaune",theme:"Green & pitch",ref:"Regle 13.1c",scene:sceneGreen(190,150),
   q:"Sur le green, peux-tu reparer une marque de chaussure (crampons) ?",
   choices:["Non","Oui, on peut reparer les marques de pas et de crampons","Seulement les pitchs","Oui, avec 1 penalite"],correct:1,
   hint:"Depuis 2019, on repare presque tout sur le green.",
   explain:"Depuis 2019, on peut reparer les marques de chaussures, de crampons, les impacts, les anciens trous... presque tous les degats du green."},
  {flag:"jaune",theme:"Securite",scene:null,
   q:"Un orage arrive et tu entends le tonnerre pendant ta partie. Que fais-tu ?",
   choices:["Je continue vite","J'arrete et je me mets a l'abri","Je leve mon club en l'air","Je cours sous un arbre isole"],correct:1,
   hint:"Rien n'est plus important que ta securite.",
   explain:"En cas d'orage, on arrete de jouer et on se met a l'abri. On ne reste pas a decouvert ni sous un arbre isole, et on ne brandit jamais son club en l'air."},
  {flag:"jaune",theme:"Regle de jeu",ref:"Regle 16.1",scene:sceneCartPath(78,150),
   q:"Ta balle repose sur une plaque ou une bouche d'arrosage (objet fixe non naturel). Tu as droit a ?",
   choices:["Rien","Un degagement gratuit a cote","Un degagement avec 1 penalite","Rejouer du depart"],correct:1,
   hint:"Un objet fixe fabrique = obstruction inamovible.",
   explain:"Une bouche d'arrosage ou une plaque est une obstruction inamovible : degagement GRATUIT a l'endroit le plus proche a cote, pas plus pres du trou."},
  {flag:"jaune",theme:"Regle de jeu",ref:"Regle 15.2",scene:sceneBunker(180,150,'<rect x="150" y="120" width="40" height="6" rx="2" fill="#8a5a2a" transform="rotate(20 170 123)"/>'),
   q:"Un rateau gene ta balle dans le bunker. Peux-tu l'enlever ?",
   choices:["Non","Oui, et si la balle bouge tu la replaces sans penalite","Seulement hors du bunker","Oui, avec 1 penalite"],correct:1,
   hint:"Le rateau est un objet qu'on peut deplacer.",
   explain:"Le rateau est une obstruction amovible : tu peux l'enlever partout. Si la balle bouge en le retirant, aucune penalite, tu la remets a sa place."},

  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 6.2b",scene:sceneTee(200,118),
   q:"Au depart, tes PIEDS peuvent-ils etre en dehors de l'aire de depart ?",
   choices:["Non, tout doit etre dedans","Oui, seule la balle doit etre dans l'aire","Non, penalite","Seulement un pied"],correct:1,
   hint:"C'est la balle qui compte, pas les pieds.",
   explain:"Seule la balle doit etre posee dans l'aire de depart. Tes pieds, eux, peuvent tres bien etre a l'exterieur. Pratique quand la balle est au bord."},
  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 9.3",scene:sceneFairway(200,150),
   q:"Tu t'installes pour jouer et la balle bouge toute seule (personne ne l'a touchee). Que fais-tu ?",
   choices:["Je la remets","Je la joue de son nouvel endroit, sans penalite","1 penalite","Je recommence"],correct:1,
   hint:"Si c'est la nature (vent, pente) et pas toi, pas de penalite.",
   explain:"Si la balle bouge a cause de forces naturelles (vent, pente) et non parce que tu l'as touchee, tu la joues de son nouvel emplacement, sans penalite (sur le green, on la replace)."},
  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 10.2b",scene:null,
   q:"Peux-tu demander a quelqu'un de se placer dans ton dos, sur ta ligne, pour t'aider a viser pendant le coup ?",
   choices:["Oui, toujours","Non, personne ne doit se tenir sur ta ligne derriere pendant que tu joues","Oui, seulement le caddie","Oui, sur le green"],correct:1,
   hint:"Viser, ca se regle avant de se placer.",
   explain:"Depuis 2019, personne (meme ton caddie) ne doit se tenir juste derriere toi sur ta ligne quand tu prends ta position pour jouer. Sinon, penalite."},
  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 5.5",scene:sceneFairway(200,150),
   q:"Pendant que tu joues un trou, peux-tu taper des balles d'entrainement ?",
   choices:["Oui, autant que je veux","Non, pas de coup d'entrainement pendant le trou","Oui, une seule","Seulement au depart"],correct:1,
   hint:"On s'entraine avant la partie, pas pendant le trou.",
   explain:"On ne joue pas de coups d'entrainement pendant qu'on joue un trou. Entre deux trous, on peut juste faire quelques putts ou chips pres du green qu'on vient de finir."},
  {flag:"blanc",theme:"Regle de jeu",ref:"Regle 20",scene:null,
   q:"En pleine partie, tu ne sais pas quelle regle appliquer. Que fais-tu ?",
   choices:["Je fais au hasard","Je demande a un arbitre, ou je note la situation pour verifier apres","J'abandonne","Je change de trou"],correct:1,
   hint:"On ne devine pas : on demande ou on verifie.",
   explain:"En cas de doute sur une regle, tu demandes a un arbitre si possible. Sinon, tu notes bien la situation (position de la balle, options prises) pour verifier apres la partie."},
  {flag:"blanc",theme:"Green & pitch",ref:"Regle 9.4",scene:sceneMarker(),
   q:"Ta balle est marquee sur le green. En la relevant, ton marqueur bouge. Penalite ?",
   choices:["Oui, 1 coup","Non, tu le remets a sa place","Oui, 2 coups","Tu rejoues"],correct:1,
   hint:"Sur le green, ces petits accidents sont pardonnes.",
   explain:"Faire bouger accidentellement son marqueur (ou sa balle) sur le green n'entraine aucune penalite : tu le remets simplement a sa place."},

  /* =======================  QUESTIONS "TOUCHE L'IMAGE"  ======================= */
  {flag:"vert",theme:"But du jeu",type:"place",scene:sceneGreen(180,150),target:{x:250,y:96,r:26},
   q:"Touche l'endroit du parcours ou se trouve le trou.",
   hint:"Il est repere par un grand poteau colore.",
   explain:"Le trou est toujours signale par un drapeau, meme visible de loin. C'est la qu'il faut faire rentrer la balle."},
  {flag:"rouge",theme:"Etiquette",type:"place",scene:sceneBag(),target:{x:340,y:120,r:30},
   q:"Tu arrives a pied au green. Touche l'endroit ou poser ton sac pour repartir vite.",
   hint:"Du cote du trou suivant, jamais sur le green.",
   explain:"On pose son sac du cote du trou suivant, jamais sur le green (trop fragile) ni loin derriere. Ainsi, une fois le trou fini, on repart tout de suite."},
  {flag:"rouge",theme:"Regle de jeu",type:"place",scene:sceneOrder(),target:{x:85,y:178,r:24},
   q:"Deux balles sont sur le green. Touche celle qui doit jouer en premier.",
   hint:"La plus loin du trou joue en premier.",
   explain:"Normalement, la balle la plus eloignee du trou joue en premier. C'est elle qui gene le moins les autres si on doit attendre."},
  {flag:"bleu",theme:"Regle de jeu",type:"place",scene:sceneTee(200,120),target:{x:200,y:108,r:62},
   q:"Touche la zone ou tu as le droit de poser ta balle au depart.",
   hint:"Entre les deux marques, jamais devant.",
   explain:"L'aire de depart se trouve entre les deux marques (et un peu derriere si besoin). Poser sa balle devant les marques n'est pas autorise."},
  {flag:"jaune",theme:"Regle de jeu",ref:"Regle 17.1",type:"place",scene:sceneWaterRed(285,140,markX(252,120)+label(252,105,"passage")),target:{x:252,y:120,r:22},
   q:"Pour te degager d'une zone rouge, touche le point a partir duquel tu mesures (la croix).",
   hint:"Jamais l'endroit final dans l'eau.",
   explain:"On mesure a partir du point ou la balle a franchi le bord de la zone (la croix), jamais depuis l'endroit ou elle a fini dans l'eau."}
];

/* ============================================================
   QUESTIONS BONUS - CULTURE GOLF (pour le plaisir, ne comptent pas)
   ============================================================ */
var BONUS = [
  {q:"Combien de Masters (la veste verte) Rory McIlroy a-t-il gagnes a ce jour ?",
   choices:["1","2","3","5"],correct:1,
   explain:"Deux : en 2025 (ce qui completait son Grand Chelem en carriere) puis en 2026, coup sur coup. Il compte 6 titres majeurs au total."},
  {q:"Quel age avait le plus jeune vainqueur de l'Open (le British Open) ?",
   choices:["17 ans","25 ans","31 ans","14 ans"],correct:0,
   explain:"Young Tom Morris a gagne l'Open a 17 ans, en 1868. Il reste le plus jeune champion de ce tres vieux tournoi."},
  {q:"Dans quel pays est ne le golf ?",
   choices:["La France","L'Ecosse","Les Etats-Unis","Le Japon"],correct:1,
   explain:"Le golf moderne est ne en Ecosse, il y a plusieurs siecles. C'est de la que viennent beaucoup de mots du golf."},
  {q:"Combien de trous compte un grand parcours de golf ?",
   choices:["9","12","18","24"],correct:2,
   explain:"Un parcours complet compte 18 trous. Beaucoup de clubs ont aussi des petits parcours de 9 trous, parfaits pour les jeunes."},
  {q:"Au golf, un 'birdie' c'est quoi ?",
   choices:["Un coup de moins que le par","Le par exactement","Un coup de plus que le par","Un oiseau sur le green"],correct:0,
   explain:"Un birdie, c'est finir un trou en un coup de MOINS que le par. Deux de moins, c'est un 'eagle' (aigle) !"},
  {q:"Quel club envoie la balle le plus LOIN ?",
   choices:["Le putter","Le driver","Le wedge","Le fer 9"],correct:1,
   explain:"Le driver est le club des grandes distances, utilise surtout au depart. Le putter, lui, sert a faire rouler la balle sur le green."},
  {q:"Combien de tournois majeurs Tiger Woods a-t-il gagnes ?",
   choices:["9","12","15","20"],correct:2,
   explain:"Tiger Woods compte 15 titres majeurs, l'un des plus grands palmares de l'histoire, derriere Jack Nicklaus et ses 18."},
  {q:"Comment appelle-t-on la personne qui porte le sac et conseille le joueur ?",
   choices:["L'arbitre","Le caddie","Le starter","Le greenkeeper"],correct:1,
   explain:"Le caddie porte le sac et peut donner des conseils au joueur (distance, choix de club, lecture du green)."},
  {q:"Lequel de ces tournois n'est PAS un majeur de golf ?",
   choices:["Le Masters","L'US Open","Roland-Garros","The Open"],correct:2,
   explain:"Roland-Garros, c'est le tennis ! Les 4 majeurs du golf sont le Masters, l'US Open, The Open (britannique) et le PGA Championship."},
  {q:"Mettre la balle dans le trou en un seul coup, ca s'appelle...",
   choices:["Un birdie","Un trou en un (hole in one)","Un eagle","Un par"],correct:1,
   explain:"C'est un 'trou en un' (hole in one) : tres rare et tres impressionnant, surtout pour les grands joueurs."},
  {q:"Une face de club plus 'ouverte' envoie plutot la balle...",
   choices:["Plus haut","Plus bas","Plus loin tout droit","Dans le trou a coup sur"],correct:0,
   explain:"Ouvrir la face ajoute de la hauteur : la balle part plus haut (et plutot vers la droite pour un droitier). La 'fermer' fait l'inverse."},
  {q:"A quoi servent les petits creux (alveoles) sur une balle de golf ?",
   choices:["A la decorer","A la faire voler plus loin et plus droit","A la rendre plus lourde","A rien"],correct:1,
   explain:"Les alveoles aident la balle a mieux fendre l'air : elle vole plus loin et plus stable qu'une balle toute lisse."},
  {q:"La Ryder Cup, c'est une competition entre...",
   choices:["Deux joueurs","L'Europe et les Etats-Unis","Tous les pays","Les clubs francais"],correct:1,
   explain:"La Ryder Cup oppose une equipe d'Europe a une equipe des Etats-Unis, tous les deux ans. Une grande fete du golf par equipes."},
  {q:"Sur le green, on fait ROULER la balle avec quel club ?",
   choices:["Le driver","Le putter","Le wedge","Le bois 3"],correct:1,
   explain:"Le putter est fait pour rouler la balle doucement sur le green, jusque dans le trou."},
  {q:"Combien de tournois majeurs Jack Nicklaus a-t-il gagnes (record) ?",
   choices:["12","15","18","20"],correct:2,
   explain:"Jack Nicklaus, surnomme 'l'Ours d'or', detient le record avec 18 titres majeurs. Une legende absolue du golf."},
  {q:"Dans quel pays se joue le Masters chaque annee ?",
   choices:["En Ecosse","Aux Etats-Unis (a Augusta)","En France","En Angleterre"],correct:1,
   explain:"Le Masters se joue chaque annee au meme endroit : le parcours d'Augusta National, aux Etats-Unis. Le vainqueur recoit une veste verte."},
  {q:"Combien de joueurs au maximum dans une partie (un 'flight') ?",
   choices:["2","4","6","8"],correct:1,
   explain:"On joue en general par groupes de 4 joueurs maximum. A plus, la partie serait bien trop lente."},
  {q:"A quel age Tiger Woods a-t-il gagne son premier Masters (record du plus jeune) ?",
   choices:["18 ans","21 ans","25 ans","30 ans"],correct:1,
   explain:"Tiger Woods a remporte le Masters 1997 a seulement 21 ans, devenant le plus jeune vainqueur de l'histoire du tournoi."}
];

/* ============================================================
   DRAPEAUX + ETAPES (progression)
   ============================================================ */
var FLAG_ORDER=["vert","rouge","bleu","jaune","blanc"];
var FLAGS={
  vert: {name:"Drapeau vert",  sub:"securite, etiquette, respect",  color:"#5fd66a", grad:"linear-gradient(135deg,#7fdc7f,#1f7a3c)"},
  rouge:{name:"Drapeau rouge", sub:"le green, le pitch, le marqueur",color:"#e0435f", grad:"linear-gradient(135deg,#e86a80,#8a1830)"},
  bleu: {name:"Drapeau bleu",  sub:"depart, ordre de jeu, rythme",  color:"#4a86e0", grad:"linear-gradient(135deg,#6f9fea,#123f9c)"},
  jaune:{name:"Drapeau jaune", sub:"regles du parcours, bunker, eau",color:"#d9c34a", grad:"linear-gradient(135deg,#e8d783,#a8901f)"},
  blanc:{name:"Drapeau blanc", sub:"autonomie, regles completes",    color:"#b8b9bd", grad:"linear-gradient(135deg,#e2e2de,#8a8b8e)"}
};
/* etape precedente requise pour debloquer (null = toujours ouvert) */
var FLAG_REQUIRES={vert:null,rouge:"vert",bleu:"rouge",jaune:"bleu",blanc:"jaune"};
function stageUnlocked(f){var req=FLAG_REQUIRES[f];if(!req)return true;return (profile.stars[req]||0)>=1;}
function mixUnlocked(){for(var i=0;i<FLAG_ORDER.length;i++){if((profile.stars[FLAG_ORDER[i]]||0)<1)return false;}return true;}

function shuffle(a){var r=a.slice();for(var i=r.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var t=r[i];r[i]=r[j];r[j]=t;}return r;}
function poolFor(f){if(f==='all')return BANK.slice();var p=[];for(var i=0;i<BANK.length;i++){if(BANK[i].flag===f)p.push(BANK[i]);}return p;}

var ETQ_THEMES={"Etiquette":1,"Comportement":1,"Securite":1,"Rapidite":1};
var recentQs={};
function notIn(list){return function(q){return list.indexOf(q)===-1;};}
function buildRound(flag){
  var pool=poolFor(flag);
  var recent=recentQs[flag]||[];
  var cand=pool.filter(notIn(recent));
  if(cand.length<TARGET){var prev=recent.slice(0,TARGET);cand=pool.filter(notIn(prev));}
  if(cand.length<TARGET)cand=pool.slice();
  var picked=shuffle(cand).slice(0,Math.min(TARGET,cand.length));
  var hasE=false;
  for(var i=0;i<picked.length;i++){ if(ETQ_THEMES[picked[i].theme]) hasE=true; }
  if(!hasE){
    var epool=cand.filter(function(q){return ETQ_THEMES[q.theme] && picked.indexOf(q)===-1;});
    if(!epool.length) epool=pool.filter(function(q){return ETQ_THEMES[q.theme];});
    if(epool.length) picked[picked.length-1]=shuffle(epool)[0];
  }
  recentQs[flag]=picked.concat(recent).slice(0,TARGET*2);
  return shuffle(picked);
}

var bonusQ=null, lastBonus=null;
function pickBonus(){
  if(!BONUS.length) return null;
  if(BONUS.length===1) return BONUS[0];
  var b; do { b=shuffle(BONUS)[0]; } while(b===lastBonus);
  lastBonus=b; return b;
}
